export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const GET_QUARTERBACKS = 'GET_QUARTERBACKS';
export const GET_QUARTERBACKS_FAIL = 'GET_QUARTERBACKS_FAIL';
export const GET_RUNNING_BACKS = 'GET_RUNNING_BACKS';
export const GET_RUNNING_BACKS_FAIL = 'GET_RUNNING_BACKS_FAIL';
export const GET_WIDE_RECEIVERS = 'GET_WIDE_RECEIVERS';
export const GET_WIDE_RECEIVERS_FAIL = 'GET_WIDE_RECEIVERS_FAIL';
export const GET_TIGHT_ENDS = 'GET_TIGHT_ENDS';
export const GET_TIGHT_ENDS_FAIL = 'GET_TIGHT_ENDS_FAIL';

export const UPDATE_USER_TEAM_SUCCESS = 'UPDATE_USER_TEAM_SUCCESS';
export const UPDATE_USER_TEAM_FAIL = 'UPDATE_USER_TEAM_FAIL';
